### ISSUE TITLE
Auth App

### ISSUE THREAD

**Issue by serobalino** [passionui/support#10]
How to integrate the Login with my Backend

`Felix Travel`

**Comment by wem-developer** [comment]
Hi. file control about navigatin './navigation/index' and  './navigation/main'
- Flow navigation https://reactnavigation.org/
Auth Flow: We connect to redux render for Screen Account
<BottomTab.Screen
        name="Profile"
        component={login ? Profile : Walkthrough}
        options={{
          title: t('account'),
          tabBarIcon: ({color}) => {
            return <Icon solid color={color} name="user-circle" size={20} />;
          },
        }}
      />

**Comment by wem-developer** [comment]
We have use React Navigation 5 and connect Redux State for build bottom navigation
