### ISSUE TITLE
No Bunddle Url present

### ISSUE THREAD

**Issue by aytaa** [passionui/support#12]
there is a error No Bunddle Url present
Can you help me ? 

![Ekran Resmi 2020-05-01 16 03 30](https://user-images.githubusercontent.com/24729859/80807232-4fb06580-8bc5-11ea-98c4-76ee59c420fe.png)

**Comment by wem-developer** [comment]
For iOS: You can try 
- npm install -> cd ios/ ->pod update->pod install
- open FelixPro.xcworkspace and build 
- after run build open terminal and run start nodeJS with cli npm start
