### ISSUE TITLE
react-native-gesture-handler

### ISSUE THREAD

**Issue by rdgcosta** [passionui/support#13]
i've been trying to open app but i got 

Unhandled JS Exception: Unexpected string literal "react-native-gesture-handler". import call expects exactly one argument.

no stack

what can i do?

**Comment by rdgcosta** [comment]
after mac reboots, it works, i really really don't know why

**Comment by wem-developer** [comment]
hi @rdgcosta 
we had import react-native-gesture-handler for react navigaiton 5
Please check more with docs: https://reactnavigation.org/docs/getting-started
