### ISSUE TITLE
Install node modules issue

### ISSUE THREAD

**Issue by Areezo** [passionui/support#14]
MacBook-Pro:source Areezo$ node -v
v10.1.0
MacBook-Pro:source Areezo$ npm -v
3.9.5

MacBook-Pro:source Areezo$ npm install
npm WARN deprecated deep-assign@3.0.0: Check out `lodash.merge` or `merge-options` instead.
npm ERR! Darwin 19.4.0
npm ERR! argv "/usr/local/Cellar/node/10.1.0/bin/node" "/Users/Areezo/.npm-packages/bin/npm" "install"
npm ERR! node v10.1.0
npm ERR! npm  v3.9.5
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/Users/Areezo/.npm-packages/lib/node_modules/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/Users/Areezo/.npm-packages/lib/node_modules/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/Users/Areezo/.npm-packages/lib/node_modules/npm/lib/install/deps.js:490:12)
npm ERR! typeerror     at /Users/Areezo/.npm-packages/lib/node_modules/npm/lib/install/deps.js:491:7
npm ERR! typeerror     at /Users/Areezo/.npm-packages/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /Users/Areezo/.npm-packages/lib/node_modules/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/Users/Areezo/.npm-packages/lib/node_modules/npm/lib/fetch-package-metadata.js:67:5)
npm ERR! typeerror     at returnAndAddMetadata (/Users/Areezo/.npm-packages/lib/node_modules/npm/lib/fetch-package-metadata.js:121:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/Users/Areezo/.npm-packages/lib/node_modules/npm/lib/fetch-package-metadata.js:138:20)
npm ERR! typeerror     at /Users/Areezo/.npm-packages/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Areezo/0Q/25-5-20/source/npm-debug.log

**Comment by wem-developer** [comment]
Hi
Please use LTS nodeJS
