### ISSUE TITLE
Lỗi khi start trên ios

### ISSUE THREAD

**Issue by taixe** [passionui/support#15]
Khi mình chạy từ simulator thì báo lỗi như hình, bạn xem giúp mình nhé. mình mới mua template của bạn và chạy thoe hướng dẫn, loay hoay cả buổi ko chưa chạy được, SDT mình : 0905999184

error: bundling failed: SyntaxError: /Users/xxx/Desktop/XX/Rent/car_rent/source/ios/app/index.js: Support for the experimental syntax 'jsx' isn't currently enabled (11:5):

   9 | export default function App() {
  10 |   return (
> 11 |     <Provider store={store}>
     |     ^
  12 |       <PersistGate loading={null} persistor={persistor}>
  13 |         <Navigator />
  14 |       </PersistGate>

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.

<img width="468" alt="Screen Shot 2020-07-31 at 17 47 02" src="https://user-images.githubusercontent.com/60805385/89028259-351d9200-d356-11ea-9e4c-272e6e3291c1.png">

**Comment by passionui** [comment]
Supported remote check
