### ISSUE TITLE
Not Building while trying to run for the first time

### ISSUE THREAD

**Issue by askvarun** [passionui/support#18]
Hi,

While trying to run the the app i have followed all the mentioned steps but after clicking on run to run the app on mobile device i am getting this error.

Execution failed for task ':app:mergeDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
     The number of method references in a .dex file cannot exceed 64K.
     Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

**Comment by askvarun** [comment]
I am on mac os 
react native version 6.13.4
Android Studio 4.0.1

**Comment by wem-developer** [comment]
Hi 
Please checkout lasted version, We are fixed
