### ISSUE TITLE
error: use of undeclared identifier 'UIActivityIndicatorViewStyleLarge'

### ISSUE THREAD

**Issue by UsmanJ** [passionui/support#21]
Hi there,
I have purchased your react native app yesterday and am having some trouble getting it running on iOS.
I get the following errors:  
`error: use of undeclared identifier 'UIActivityIndicatorViewStyleLarge'`

and

`error: use of undeclared identifier 'UIActivityIndicatorViewStyleMedium'; did you mean 'UIActivityIndicatorViewStyleWhite'?`

Please can you advise on how to fix this?

Also - is it possible to run the app in web mode whilst dev'ing?

**Comment by wem-developer** [comment]
Hi
let me know you are getting error the origin lasted source at codecanyon
If you are customize, Please send to me git diff
Thanks

**Comment by UsmanJ** [comment]
Hello Wem,

Are you able to jump on a call?

It is happening since I downloaded the source code but I have since then made changes.


Thanks,
Usman

Usman Jamil
M: +44 7415121250

________________________________

**Comment by UsmanJ** [comment]
Issue resolved. Was running an older version of xCode which was causing the issue.
