### ISSUE TITLE
How to change languages?

### ISSUE THREAD

**Issue by Nimto007** [passionui/support#4]
I want to switch language, how can I do that?

**Comment by rickchew** [comment]
same question, i'm now studying [https://github.com/w4mxl/V2LF](https://github.com/w4mxl/V2LF) , they are using same structure refer to this file [https://github.com/w4mxl/V2LF/blob/master/lib/models/language.dart](https://github.com/w4mxl/V2LF/blob/master/lib/models/language.dart)

**Comment by wem-developer** [comment]
We will release feature multilanguage and RTL UI support Listar Flux in next week. Thanks for your feedback.

**Comment by wem-developer** [comment]
New release Listar Flux avaliable feature multi language and RTL support. Please try it
