### ISSUE TITLE
Issue with Listar Fluw

### ISSUE THREAD

**Issue by wytex** [passionui/support#8]
Hi Running emulator I got this error:

`Running Gradle task 'assembleDebug'...

Compiler message:
lib/screens/screen.dart:15:1: Error: Error when reading 'lib/screens/intro_preview/intro_preview.dart': No such file or directory
export 'intro_preview/intro_preview.dart';
^
lib/app.dart:81:30: Error: The method 'IntroPreview' isn't defined for the class '_AppState'.
 - '_AppState' is from 'package:listar_flutter/app.dart' ('lib/app.dart').
Try correcting the name to the name of an existing method, or defining a method named 'IntroPreview'.
                      return IntroPreview();
                             ^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script '/home/wytex/Desktop/devMobile/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/wytex/Desktop/devMobile/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Finished with error: Gradle task assembleDebug failed with exit code 1`

**Comment by wem-developer** [comment]
Thank you for feedback, I have a question. Do you have merge code from old version to lasted? You can give me information teamviewer I'll connect to your computer for check it

**Comment by wem-developer** [comment]
You can zip and send to me your project fail build via wem.passionui@gmail.com I'll help you detect issue.

**Comment by wem-developer** [comment]
Thank you so much. Let try lasted release avaliable on envato
![image](https://user-images.githubusercontent.com/58037654/74996979-98da8f80-5487-11ea-8ca3-5bd38a7afc24.png)
